<?php

namespace MiningManager\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class ReportSchedule extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'report_schedules';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'report_type',
        'format',
        'frequency',
        'run_time',
        'is_active',
        'last_run',
        'next_run',
        'reports_generated',
        'send_to_discord',
        'webhook_id',
        'created_by',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'is_active' => 'boolean',
        'send_to_discord' => 'boolean',
        'last_run' => 'datetime',
        'next_run' => 'datetime',
    ];

    /**
     * Get the reports generated by this schedule.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function reports()
    {
        return $this->hasMany(MiningReport::class, 'schedule_id');
    }

    /**
     * Get the webhook configuration for Discord notifications.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function webhook()
    {
        return $this->belongsTo(WebhookConfiguration::class, 'webhook_id');
    }

    /**
     * Calculate and set the next run time based on frequency and run_time.
     *
     * @param Carbon|null $from Base time to calculate from (defaults to now)
     * @return Carbon
     */
    public function calculateNextRun(?Carbon $from = null): Carbon
    {
        $from = $from ?? Carbon::now();

        // Parse the run_time (HH:MM) for the target hour/minute
        $timeParts = explode(':', $this->run_time);
        $hour = (int) ($timeParts[0] ?? 0);
        $minute = (int) ($timeParts[1] ?? 0);

        switch ($this->frequency) {
            case 'daily':
                $next = $from->copy()->setTime($hour, $minute, 0);
                if ($next->lte($from)) {
                    $next->addDay();
                }
                break;

            case 'weekly':
                // Next Monday at the specified time
                $next = $from->copy()->next(Carbon::MONDAY)->setTime($hour, $minute, 0);
                if ($next->lte($from)) {
                    $next->addWeek();
                }
                break;

            case 'monthly':
                // 1st of next month at the specified time
                $next = $from->copy()->addMonthNoOverflow()->startOfMonth()->setTime($hour, $minute, 0);
                if ($next->lte($from)) {
                    $next->addMonthNoOverflow();
                }
                break;

            default:
                $next = $from->copy()->addDay()->setTime($hour, $minute, 0);
                break;
        }

        $this->next_run = $next;

        return $next;
    }

    /**
     * Get the date range for the current run based on report_type.
     *
     * Daily: yesterday's full day
     * Weekly: last 7 days
     * Monthly: the entire previous month
     *
     * @return array [Carbon $startDate, Carbon $endDate]
     */
    public function getDateRangeForRun(): array
    {
        $now = Carbon::now();

        switch ($this->report_type) {
            case 'daily':
                return [
                    $now->copy()->subDay()->startOfDay(),
                    $now->copy()->subDay()->endOfDay(),
                ];

            case 'weekly':
                return [
                    $now->copy()->subDays(7)->startOfDay(),
                    $now->copy()->subDay()->endOfDay(),
                ];

            case 'monthly':
                return [
                    $now->copy()->subMonthNoOverflow()->startOfMonth(),
                    $now->copy()->subMonthNoOverflow()->endOfMonth(),
                ];

            default:
                return [
                    $now->copy()->subDay()->startOfDay(),
                    $now->copy()->subDay()->endOfDay(),
                ];
        }
    }
}
